osmc/osmc

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/bluetooth.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/bluezutils.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/connman.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmc_bluetooth.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmc_bluetooth_agent.py
Pairing agent is a seprate python script that  currently relies on console but we need to replace this with XBMC dialogues/Inputs
> Bluetooth python modules and pairing agent

- wiki/pages/pi-blackscreen
thisis has been split into two words.
> Minor typo

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/language/English/strings.po
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/networking_gui.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmc_network.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/skins/Default/1080i/network_gui.xml
Note this has NOT been tested on a true NFS install as I don't have one set-up 
Testing was done with dummy /proc/cmdline and /boot/cmdline file stored in the home directory but the appeared to be parsed and updated correctly
> Fixes to wired network GUI when running a NFS install

- package/mediacenter-skin-osmc/files/usr/share/kodi/addons/skin.osmc/16x9/Startup.xml
- package/mediacenter-skin-osmc/files/usr/share/kodi/addons/skin.osmc/addon.xml
- package/mediacenter-skin-osmc/files/usr/share/kodi/addons/skin.osmc/changelog.txt
> [package] [mediacenter-skin-osmc]

- wiki/pages/console
More specifically advised user:pass as osmc:osmc.  Moved Exit Kodi to top of list
> [wiki] minor edits to console page

- wiki/pages/logs
> [wiki] logging changes

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/skins/Default/1080i/network_gui.xml
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/skins/Default/1080i/network_gui_720.xml
Fix dark selections, turn them back to white.
> [package] [mediacenter-addon-osmc] Wifi Selection Brighter

- package/mediacenter-osmc/patches/all-001-system-info-display.patch
15.0-ALPHA1 will be 15.0
15.1-RC1 will be 15.1
> Cosmetic: show Kodi version in system info (only version number)

- package/mediacenter-osmc/patches/all-001-system-info-display.patch
Sorry @samnazarko 
Just updated my osmc
> Cosmetic - Fix display of Kodi version

- installer/host/osmc-installer.spec
Reference discussion: https://discourse.osmc.tv/t/osmc-installer/12140/3
> Use isa macro under Fedora.

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/language/English/strings.po
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/lib/OSMC_REparser.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/settings.xml
Added support for Allo Piano DAC
> Support for Allo Piano DAC 

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/language/English/strings.po
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/lib/OSMC_REparser.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/settings.xml
Support for Allo Boss HiFi DAC
> [package] [mediacenter-addon-osmc] Added support for Allo Boss DAC

- package/tvheadend-app-osmc/build.sh
- package/tvheadend-app-osmc/files/DEBIAN/postinst
Removed an exit in postinst which may be causing reports of ppl having to delete user file.
Enabled CI support.
> [package][tvheadend-app-osmc] CI support and improve installer

- package/tvheadend-app-osmc/files/DEBIAN/postinst
Fix for problem reported earlier today
> [package][tvheadend-app-osmc] Improve first-time installation

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.logging/resources/lib/grablogs.py
So kodi and kernel logs can be matched
> [package][mediacenter-addon-osmc] Add uptime to header

- package/kernel-osmc/build.sh
- package/kernel-osmc/initramfs-src/build.sh
Signed-off-by: David <db@d1b.org>
> Update the location of sources used to build osmc kernels.

- package/mediacenter-addon-osmc/files/DEBIAN/control
- package/mediacenter-addon-osmc/src/script.module.osmccommon/resources/lib/grablogs.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.logging/resources/language/English/strings.po
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.logging/resources/lib/grablogs.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.logging/resources/settings.xml
This patch is to add guisettings into the grab-logs capability with the purpose of being able to share the audio settings. As discussed with @KODeKarnage on slack
> Add guisettings logging

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/language/English/strings.po
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/lib/OSMC_REparser.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/settings.xml
Adding support for Allo Digione Card
> [package] [mediacenter-addon-osmc] Adding support for Allo Digione Card

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.updates/resources/lib/apt_cache_action.py
Also prevented div by zero in it's pulse method.
> Initialize fetching for Download_Progress.

- package/mediacenter-osmc/patches/vero3-128-add-bitdepth-to-hints.patch
> [package][mediacenter-osmc]Add bitdepth to hints

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.apfstore/resources/skins/Default/1080i/APFBrowser_720OSMC.xml
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.apfstore/resources/skins/Default/1080i/APFBrowser_OSMC.xml
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.remotes/resources/skins/Default/1080i/RemoteBrowser_720OSMC.xml
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.remotes/resources/skins/Default/1080i/RemoteBrowser_OSMC.xml
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.services/resources/skins/Default/1080i/ServiceBrowser_720OSMC.xml
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.services/resources/skins/Default/1080i/ServiceBrowser_OSMC.xml
remove broken "views" lines from MyOSMC app store, remotes and services sections
> MyOSMC Leia focus fix

- package/mediacenter-osmc/patches/vero3-143-HDMI-hotplug-detection.patch
> [package] [mediacenter-osmc] Add back HDMI hotplug detection

- package/mediacenter-osmc/patches/vero3-066-fix-deinterlacing-of-progressive.patch
I think this is what you meant?
> [package][mediacenter-osmc] fix VC-1 again again

- package/mediacenter-osmc/patches/all-121-prefer-higher-res-at-framerate.patch
> [package][mediacenter-osmc] Prefer higher res at correct frame rate

- package/mediacenter-osmc/patches/all-121-prefer-higher-res-at-framerate.patch
This should work for Leia.  Previous version was against Matrix.
> [package][mediacenter-osmc] fix all-121 patch for Leia

- installer/host/qt_host_installer/deviceselection.ui
- installer/host/qt_host_installer/extractprogress.cpp
- installer/host/qt_host_installer/extractprogress.ui
- installer/host/qt_host_installer/osmc.ts
- installer/host/qt_host_installer/preseeddevice.ui
May help users understand the install options better.
> [installer] More Vero-centric prompts

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.logging/resources/lib/readgui.py
Adds parsing to refresh rate and shows whitelists.
Changed the default user to always be osmc instead of the user that's running the script.
Python 2/3 compatibility fixes.
> [package] [mediacenter-addon-osmc] Add parsing of refresh rate. Default home to osmc

- package/mediacenter-osmc/patches/vero3-168-fix-audio-for-4.9.patch
provision for 4.9 card names;
tidied up audio sink names
> Fixed missing stereo on HDMI;

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.logging/resources/settings.xml
Current defaults deselects all configs and logs which is obviously wrong.
> Update settings.xml, defaults should select all configs and logs

- .gitignore
- package/ftr-osmc/files/DEBIAN/control
- package/ftr-osmc/files/usr/bin/preseed
- package/ftr-osmc/files/usr/bin/preseed-agent
>  [package][ftr-osmc] Python 2/3 compatibility

- package/mediacenter-addon-osmc/src/script.module.osmccommon/resources/lib/osmccommon/grablogs.py
- fix grab-logs -P (again)
- only add raspberry pi logs to grab-logs output if it's ran from a pi
> [package] [mediacenter-addon-osmc] fix grab-logs -P, clean up vero grab-logs

- package/mediacenter-addon-osmc/src/service.osmc.settings/resources/lib/osmcsettings/fonts.txt
- package/mediacenter-addon-osmc/src/service.osmc.settings/resources/lib/osmcsettings/osmc_ubiquifonts.py
- previously these fonts were only added to the first fontset
- now switching to another font -ie. Arial in skin.osmc- My OSMC will remain consistent
> [package] [mediacenter-addon-osmc] Import Ubiqui fonts to all fontsets provided by the active skin

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/language/resource.language.en_gb/strings.po
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/lib/osmcpi/config_editor.py
-  update pi strings to refer to config-user.txt
- ignore comments for config-user.txt dupe check
> [package] [mediacenter-addon-osmc] Pi Config Editor updates

- package/mediacenter-addon-osmc/src/script.module.osmccommon/resources/lib/osmccommon/grablogs.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.remotes/resources/lib/osmcremotes/remote_gui.py
- package/mediacenter-addon-osmc/src/service.osmc.settings/resources/lib/osmcsettings/osmc_settings_gui.py
- package/mediacenter-addon-osmc/src/service.osmc.settings/resources/lib/osmcsettings/osmc_walkthru.py
- package/mediacenter-addon-osmc/src/service.osmc.settings/resources/lib/osmcsettings/service_entry.py
This fixes MyOSMC on bullseye.
> [package] [mediacenter-addon-osmc] fix usage of deprecated threading methods

- package/mediacenter-osmc/patches/rbp2-watchdog
- package/mediacenter-osmc/patches/rbp4-watchdog
- package/mediacenter-osmc/patches/vero3-watchdog
User now has login default timeout (60s) to enter password
in addition to 30s to enter username
set_font enabled
Escape key now works after bringing up Power menu with keyboard S
> [package][mediacenter-osmc] Improve tty console

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/osmc_network.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/osmc_wireless_agent.py
This reverts commit 352c0dc766f6da993a7fffea4f182ae0f0d9c376.
Preseed remains broken
> [package] [mediacenter-addon-osmc]  Revert "add connman provisioning updates"

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/osmc_bluetooth.py
- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/osmc_bluetooth_agent.py
Since Python 3.8, we can no longer invoke the agent with os.fork
which is used by Pexpect.  Also, Kodi doesn't import gi.repository
needed for GLib which is the only asynchronous context supported by python-dbus.
So re-wrote the agent to use dbussy and ravel with asyncio. The rest of the
addon's dbus interaction remains based on python-dbus.
> [package][mediacenter-addon-osmc] Update bluetooth pairing agent

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py
Also disabled busy dialog to avoid warnings
> [package][mediacenter-addon-osmc] Add bluetooth disconnect option

- package/mediacenter-addon-osmc/src/script.module.osmcsetting.updates/resources/lib/osmcupdates/osmc_backups.py
[package] [mediacenter-addon-osmc] fixup backup verification to smb://
> [package] [mediacenter-addon-osmc] fixup backup verification to smb://
