wiki/pages/airplay

Perhaps wrapping should be left to the text editor :-). This might be a common mistake that is not clearly visible when editing the file on github.

Another missing space

---

package/mediacenter-skin-osmc/files/usr/share/kodi/addons/skin.osmc/16x9/Startup.xml

As discussed this checks if the walk through is running and waits until it's finished before loading the home screen.

[package] [mediacenter-skin-osmc] startup changes

---

installer/host/qt_host_installer/main.cpp

Calling raise() on the window is needed for it to launch in the foreground on OS X.

Raise the window

---

package/ssh-app-osmc/files/etc/ssh/sshd_config

The motd is printed two times because it's already handled by /etc/pam.d/sshd

Fix printing the MOTD a second time

---

package/remote-osmc/files/etc/lirc/hauppage45-pvr350-lircd.conf
package/remote-osmc/files/etc/lirc/lircd-full.conf

The "volume down" and "pictures" buttons on my Hauppauge 350 remote weren't working. After this small correction they're doing what they're supposed to.

Fix broken buttons (volume down & pictures) on Hauppauge 350 remote.

---

installer/host/qt_host_installer/qt_host_installer.pro
installer/host/qt_host_installer/utils.h
installer/host/qt_host_installer/wifinetworksetup.ui

inputMethodHints have been set automagically by Creator to reflect the password property. See http://doc.qt.io/qt-5/qt.html#InputMethodHint-enum for details on why they are relevant.
For example, you want Qt::ImhNoPredictiveText to avoid dictionary lookups - no use to have your password searched for in cleartext around places :)

[installer][host] make Textfield for WIFI Key a real Password-Field.

---

installer/host/qt_host_installer/osmcinstaller

As discussed here[1], setting QT_X11_NO_MITSHM=1 fixes issues at least in Debian
testing and, as Sam said, should not hurt others.
I have tested this patch and it works on Debian testing.
[1]: https://discourse.osmc.tv/t/osmcinstaller-does-not-work-on-debian-testing/10163/9
Signed-off-by: Rodrigo Campos <rodrigo@sdfg.com.ar>

[installer] [host] Linux: Fix errors with latest distributions

---

installer/host/osmc-installer.spec

Change day of the week to the correct one. OBS can't build without the correct date.

[installer] [host] Fix bad changelod date

---

package/mediacenter-addon-osmc/src/script.module.osmcsetting.updates/resources/lib/simple_scheduler.py

Initial date setting in the simple scheduler fails on Feb 29 because
it doesn't use a leap year. Feb 29 is only valid on leap years so use
one to stop a datetime exception and subsequent user error message about
a failed update.

Don't throw an error updating on Feb 29

---

package/mediacenter-addon-osmc/src/service.osmc.settings/resources/lib/osmc_walkthru.py

OSMC Waltkthru would hang when clicking 'continue' on the license accept panel if there was no network.
This was due to originally the function call missing the controlID argument.
The quick fix for this was also causing an error due to passing 2x arguments ('self' which is not needed in Python). 
The still_checking_for_network function doesn't actually use the controlID argument, so this PR reverts the function call back to original and removes the argument from the function. There are no other calls to this function so no "breakages" elsewhere.
(Sorry for the 2nd pull request. I'm new to this.)

Fix OSMC walkthru hanging if no network detected

---

package/libsqlite-osmc/build.sh
package/libsqlite-osmc/files/DEBIAN/control

Fix to avoid potentially sleeping for 1 second when <1 second required
Add -DHAVE_USLEEP=1 to compile-time options

[package] [libsqlite-osmc] Fix to avoid potentially over sleeping

---

package/eventlircd-osmc/files/lib/udev/rules.d/98-eventlircd.rules

Fix udev "name" attribute for devices created by CWiid / wminput

[package][eventlircd-osmc] Fix wminput device udev name

---

package/libcec-osmc/patches/all-005-config-option-power-up-avr.patch
package/mediacenter-osmc/patches/all-070-add-configuration-option-autowake-avr.patch

This will patch libcec to add in the changes added in libcec 4.0.0 that makes automatically waking any audiosystems a configuration option.
The default value is 0 so it will not automatically power up audiosystems, but I`m not sure how this option can be changed outside of the code.

[package] [libcec-osmc] Add patch to backport AVR auto wake changes

---

package/kernel-osmc/initramfs-src/init

this can be useful using an NFS root filesystem on a server that could be temporarily not available
I use 3 RPis in the nfs-root setting with great satisfaction but I would make my RPis to automatically reboot if the NFS server is down or restarted. I already use the `watchdog` package to continuously ping the server but if it is down at the RPi startup, the latter drop on the rescue shell and this requires a manual action. This option would solve my problem.

[package] [kernel-osmc] initramfs: added kernel option `rebootonerror` to auto-reboot on root fs mount error

---

package/tvheadend-app-osmc/build.sh

./configure prefix defaults to /usr/local. The systemd service expects the binary to live in /usr/bin, so it can't get started. Tested armv7-version (rpi3).
Thanks for the great work!

[package] [tvheadend-app-osmc] Fix path prefix

---

package/mediacenter-addon-osmc/files/DEBIAN/control
package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/lib/OSMC_REparser.py
package/mediacenter-addon-osmc/src/script.module.osmcsetting.pi/resources/settings.xml

On my setup, I need to define the gpio_in_pin for LIRC to 26. According to [raspberrypi.org](https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/), RPi 2 & 3 can use GPIO up to 27.
So I propose to set the limit to 27 for gpio_in_pin and gpio_out_pin.

[package] [mediacenter-addon-osmc] Allow GPIO pins > 25 for LIRC configuration

---

package/diskmount-osmc/files/etc/udisks-glue.conf

Samba Netbios name is the short hostname (as returned by 'hostname -s'). Without this modification, Samba usershares do not work when the machine has a FQDN (as returned by 'hostname').

[package] [diskmount-osmc] Samba usershares: use short hostname

---

package/mediacenter-addon-osmc/files/DEBIAN/control
package/mediacenter-addon-osmc/src/script.module.osmccommon/resources/lib/grablogs.py
package/mediacenter-addon-osmc/src/script.module.osmcsetting.logging/resources/lib/grablogs.py

Not sure about package/mediacenter-addon-osmc/src/script.module.osmccommon/resources/lib/grablogs.py line 221 change, I think it was a $ sign which should now be in 227

[package] [mediacenter-addon-osmc] Add logging of APT sources.list.d

---

package/eventlircd-osmc/files/etc/eventlircd.d/t3_airmouse.evmap
package/eventlircd-osmc/files/lib/udev/rules.d/98-eventlircd.rules

This particular one seems to go by many brand names online. Info and pictures on one of these can be found [here](https://www.amazon.com/Keenest-Wireless-Keyboard-Multifunctional-3-Gsensor/dp/B01CEWV2BW/189-2112597-2293766)
This is to solve a question I started at the OSMC forum [here](https://discourse.osmc.tv/t/custom-hwdb-not-working/54550).

Adding eventlircd maps for FreeWay T3 RF/IR Air-Mouse.

---

package/kernel-osmc/patches/rbp-038-GeniatechHDStar3.patch

To address this issue:
https://discourse.osmc.tv/t/geniatech-hdstar-v3-dvb-s2-not-working/12758
Pull in the changesets from https://bitbucket.org/updatelee/v4l-updatelee to make this adapter work.
> 
> 55c63982a513c93bdd42034f3353395c3cc4b4f8 (Bill Murphy, CrazyCat) [PATCH] [media] dw2102: Combine SU3000 (and OEM) support.
>  Thanks crazycat. fixes Geniatech SU3000 v3.0 hardware, by providing a method to
>  detect Montage ds3000 or m88ds3103 demod. Then attaching the proper demod
>  module. SU3000 v3.0 hardware has ts2022/m88ds3103 chips on board and the
>  ds3000 module previously wasn't working with this hardware. We now attach the
>  proper m88ds3103 demod for rev3, and ds3000 for the older versions.
> 
> Part of:
> 646903c536513c83b1775218676dcad6065abe73 (Bill Murphy, DarkSky) …

Support Geniatech HDStar v3

---

package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/networking_gui.py

If advancedsettings had empty videolibrary tags, MyOSMC raises and exception and does not save the user information.

Fixed exception with MyOSMC

---

package/mediacenter-osmc/patches/vero3-128-keep-desktop-mode-on-EDID-read.patch

However we trigger a disp_cap re-read, we will need this.  Otherwise, the desktop mode in settings gets lost.

[package][mediacenter-osmc] Keep desktop mode when re-reading EDID

---

package/mediacenter-osmc/patches/vero3-128-add-bitdepth-to-hints.patch

This does very little but opened a code formatting can of worms in DVDDemuxFFmpeg.

[package][mediacenter-osmc]Add bitdepth to hints

---

installer/target/qt_target/qt_target_installer/extractworker.cpp
installer/target/qt_target/qt_target_installer/mainwindow.cpp

This allows to restore the filesystem from an uncompressed tarball.  Packing/unpacking is 8x faster than compressing it with xz.
Tested the -a switch works with filesystem.tar and filesystem.tar.xz.  Not built and tested.

[installer][target] Allow uncompressed tar for filesystem

---

package/mediacenter-osmc/patches/vero3-144-find-best-resolution-on-edid-change.patch

If device is started with no EDID available or the display device is changed by hotplugging or switching in AVR, resolution is now set to the previous setting or closest match.

[package] [mediacenter-osmc] Fix resolutions on edid change

---

package/mediacenter-osmc/patches/vero3-159-show-NTSC-PAL-in-original-res.patch

Fixes letterboxing on 576p and 480p video when played at source resolution.

[package][mediacenter-osmc] Show TV/DVD streams in original resolutions

---

package/mediacenter-osmc/patches/vero3-159-show-NTSC-PAL-in-original-res.patch

Fixes scaling for whitelisted SD modes using SW decoding and should fix live TV streams with weird metadata.  Needs testing.

[package][mediacenter-osmc] Fix aspect ratios for TV HW and SW decoding

---

package/mediacenter-osmc/patches/vero3-159-show-NTSC-PAL-in-original-res.patch

Add back requirement for OSD setting to be Normal

[package][mediacenter-osmc] Exclude > 720 width from a/r signalling

---

package/mediacenter-osmc/patches/all-122-add-support-for-bluealsa.patch

Provides for each BT audio device to be enumerated and appear in audio settings.
Currently needs a list of devices in .asoundrc.
Tested on Vero4k+ only but should be OK on other devices.

[package][mediacenter-osmc] Add support for bluealsa

---

package/mediacenter-osmc/patches/all-124-guiinfo-DisplayAfterSeek-should-not-return-True-if-p.patch

Gets rid of 2.5s delay with progress bar on screen after pause.  It's in Matrix but seems unlikely to be backported to Leia. @Ch1llb0 request.

[package][mediacenter-osmc] Turn off GUI on unpause

---

package/mediacenter-addon-osmc/src/script.module.osmcsetting.logging/resources/settings.xml

Current defaults setting for label 32002 deselects all configs and logs which is obviously wrong.

Update settings.xml, defaults should select all logs and configs

---

package/mediacenter-osmc/patches/all-125-fix-quirky-USB-audio-card.patch

https://discourse.osmc.tv/t/vero-4k-lost-7-1-analogue-output-after-june-update/86186/
Tested for regressions.  Not yet tested by the user.

[package][mediacenter-osmc] Fix for USB soundcard with bad channelmap

---

package/mediacenter-osmc/patches/vero3-144-find-best-resolution-on-edid-change.patch

Helps with spurious display modes put out by AVRs, HDMI converters etc when main display is turned off.

[package][mediacenter-osmc] Ignore VESA modes if not selected as DESKTOP

---

package/mediacenter-addon-osmc/src/script.module.osmcsetting.apfstore/resources/lib/apfstore/apf_class.py
package/mediacenter-addon-osmc/src/script.module.osmcsetting.apfstore/resources/lib/apfstore/apf_store.py
package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py
package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/osmc_advset_editor.py
package/mediacenter-addon-osmc/src/script.module.osmcsetting.updates/resources/lib/osmcupdates/osmc_backups.py
package/mediacenter-addon-osmc/src/script.module.osmcsetting.updates/resources/lib/osmcupdates/service_entry.py
package/mediacenter-addon-osmc/src/service.osmc.settings/resources/lib/osmcsettings/osmc_ubiquifonts.py
package/mediacenter-addon-osmc/src/service.osmc.settings/resources/lib/osmcsettings/osmc_walkthru.py

WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.

[package] [mediacenter-addon-osmc] resolve warning for use of deprecated method

---

package/mediacenter-addon-osmc/src/script.module.osmcsetting.logging/resources/lib/osmclogging/readgui.py

Fixed grab-logs GUI Settings (abridged) Output:
====================== GUI Settings (abridged) =================== z9Z12KgS
Dolby Digital (AC3) capable receiver: true
Enable Dolby Digital (AC3) transcoding: false
Audio output device: ALSA:default
Number of channels: 3.1 ===> Default: 2.0
Output configuration: Best match
DTS-HD capable receiver: false
DTS capable receiver: true
Dolby Digital Plus (E-AC3) capable receiver: false
Play GUI sounds: Only when playback stopped
Allow passthrough: false
TrueHD capable receiver: false
Adjust display refresh rate: Off
Sync playback to display: false
Disable stereoscopic 3D mode when playback ended: true
Playback mode of stereoscopic 3D videos: Ask me
Display 4:3 videos as: Normal
Enable HQ scalers for scaling above: 20
Allow hardware acceleration - …

[package] [mediacenter-addon-osmc] fix grab-logs GUI Settings (abridged)

---

package/kernel-osmc/patches/vero364-000-add-kernel-config.patch

Brings 4.9 kernel on Vero into line with 3.14 and RPi kernels

[package][kernel-osmc] Add snd_aloop for Vero3

---

package/kernel-osmc/initramfs-src/init.d/vero364

Use 1080p or 1080i if it exists so avoid scaling by ply-image for HD-Ready and 4K displays.

[package][kernel-osmc] Improve splash rendering

---

package/base-files-osmc/files/usr/bin/apt-get

https://discourse.osmc.tv/t/different-apt-get-upgrade-restriction/84053

Proposed fix for forum thread #84053: different apt get upgrade restriction

---

package/bluez-osmc/build.sh

This PR sets the `--enable-sixaxis` build flag on bluez so that PS3 controllers can be easily paired wirelessly with OSMC devices.

[package] [bluez-osmc] Enable Sixaxis (PS3 controller) plugin

---

package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/osmc_bluetooth.py

https://discourse.osmc.tv/t/testing-kodi-v19-builds-for-vero-4k-4k/89151/620

[package] [mediacenter-addon-osmc] fix bluetooth devices without Class not being listed

---

package/kernel-osmc/files/DEBIAN/control

Indicates kernel already provides `wireguard.ko` so `wireguard-dkms` is unnecessary when installing `wireguard` package.
See [Discourse thread](https://discourse.osmc.tv/t/91569) for context.

[package] [kernel-osmc] Provide wireguard-modules

---

package/kernel-osmc/build.sh
package/kernel-osmc/files/DEBIAN/control

This is a correction to https://github.com/osmc/osmc/pull/671, which didn't take the kernel package architecture into account.
On platforms where the kernel and user space architectures differ, the kernel must provide "wireguard-modules" in the user space architecture to satisfy the "wireguard" package dependency.

[package] [kernel-osmc] Fix wireguard-modules architecture

---

package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/language/resource.language.en_gb/strings.po
package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py
package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/osmc_bluetooth.py
package/mediacenter-addon-osmc/src/script.module.osmcsetting.networking/resources/lib/osmcnetworking/osmc_bluetooth_agent.py

Syntax changes to work with python 3
Remove deprecated GObject use
Removed Connect without PIN - bluez should automatically choose
pairing method according to device capabilities (BT version support)

[package][mediacenter-addon-osmc] Fix BT pairing for Python 3

---

installer/host/qt_host_installer/io_osx.cpp
installer/host/qt_host_installer/main.cpp

Script now uses retaliative path instead of absolute. When the installer is run the working directory is changed to the resources folder. Change on affects apple/osx.

Fix 'sudo-askpass.osascript.js: No such file or directory'

---

package/ftr-osmc/files/usr/bin/preseed

base64.b64encode function takes a bytes-like object as parameter Previously a simple string object was passed to it, which raised a TypeError. This resulted in a faulty preseed WiFi configuration making WiFi basically useless when booting up OSMC, because it prevented connecting to any kind of WiFi network manually on the GUI, too. Added the necessary bytes conversion of the parsed SSID and also joined the double variable assignments into one, so now it encodes, decodes the parsed SSID and finally strips the base64 encoded string in one step. Also fixed a typo made in the preseed provisioning file name: conmann -> connman

[package] [ftr-osmc] Fix SSID base64 encoding

---

package/mediacenter-addon-osmc/src/script.module.osmccommon/resources/lib/osmccommon/grablogs.py

cta_cap prints only CTA modes as implied by the section heading

[package][mediacenter-addon-osmc] grablogs - change to cta_cap

---

package/aml-vnc-app-osmc/app.json
package/aml-vnc-app-osmc/build.sh
package/aml-vnc-app-osmc/files/DEBIAN/control
package/aml-vnc-app-osmc/files/lib/systemd/system/aml-vnc.service

The VNC server crashes on first connection after boot because it starts earlier than Kodi and starts with incorrect resolution/color scheme. Delaying the start of the service solves this issue.
In addition, a few minor build corrections, which are highlighted in review comments.

[package] [aml-vnc-app-osmc] Fix service crash on first connection after boot

---

package/aml-vnc-app-osmc/app.json
package/aml-vnc-app-osmc/build.sh
package/aml-vnc-app-osmc/files/DEBIAN/control

Fixed server performance issues on OSMC 2023-12 release.
**Reference:**
https://www.youtube.com/watch?v=OUXYszop0t0
**Changes:**
- fix pixel comparison between VNC image buffer and framebuffer,
- reset comparison matrix grid distance from 12x12 to 4x4, because dirty regions remain when using some Kodi skins,
- filling image buffer in every line with memcpy, instead of filling from byte to byte by a for loop.
**Here is a binary package for testing, built from the same code base:**
https://libreelec.dtech.hu/.upload/armv7-aml-vnc-app-osmc_1.0.1-0pre1_armhf.deb
**Additional steps required before merging:**
- Please add a `1.0.1` tag to this commit: https://github.com/osmc/aml-vnc-server/commit/57e041342a5ae0fc3de7573ca43d31cef033a62a.

[package] [aml-vnc-app-osmc] Bump to 1.0.1-1

---

package/aml-vnc-app-osmc/app.json
package/aml-vnc-app-osmc/build.sh
package/aml-vnc-app-osmc/files/DEBIAN/control

Update package source to AML-VNC Server v1.1.0.
**Additional steps required before merging:**
- Please merge this PR in the source repository:
https://github.com/osmc/aml-vnc-server/pull/2
- Please also add a `1.1.0` tag to the last commit after the merge.

[package] [aml-vnc-app-osmc] Bump to 1.1.0-1

---

package/aml-vnc-app-osmc/app.json
package/aml-vnc-app-osmc/build.sh
package/aml-vnc-app-osmc/files/DEBIAN/control

Update package source to AML-VNC Server v1.2.0.
**Additional steps required before merging:**
- Please merge this PR in the source repository:
https://github.com/osmc/aml-vnc-server/pull/3
- Please also add a `1.2.0` tag to the last commit after the merge.

[package] [aml-vnc-app-osmc] Bump to 1.2.0-1

---

package/mediacenter-addon-osmc/src/script.module.osmcsetting.updates/resources/lib/osmcupdates/osmc_hotfix.py

- attempt to find and download hotfixes from https://ftp.fau.de/osmc/osmc/download/hotfixes/ first
- if hotfix available from https://ftp.fau.de/osmc/osmc/download/hotfixes/ remove "Only use Hotfixes provided by people you trust." from confirmation dialog

[package] [mediacenter-addon-osmc] add hotfix retrieval from osmc mirrors

---

package/aml-vnc-app-osmc/app.json
package/aml-vnc-app-osmc/build.sh
package/aml-vnc-app-osmc/files/DEBIAN/control

Update package source to AML-VNC Server v1.2.1.
**Additional steps required before merging:**
- Please merge this PR in the source repository:
https://github.com/osmc/aml-vnc-server/pull/4
- Please also add a `1.2.1` tag to the last commit after the merge.

[package] [aml-vnc-app-osmc] Bump to 1.2.1-1
